# Configuração do Projeto
sonar.projectKey=portal-api
sonar.projectName=Portal API
sonar.projectVersion=1.0

# Configuração do Código
sonar.sources=src/main/java
sonar.language=java
sonar.sourceEncoding=UTF-8

# Configuração do Servidor
sonar.host.url=http://localhost:9000
sonar.login=sqp_25d2b80b3bed9918ae6fcca437ae48d04887edee