CREATE TABLE sec_permissao (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO sec_permissao (id, nome) values (1, 'ROLE_CADASTRAR_PARAMETROS');
