CREATE TABLE files (
	id BIGINT(20) PRIMARY KEY,
	name VARCHAR(50),
	type VARCHAR(50) NOT NULL,
	data MEDIUMBLOB DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `portaldb`.`files`
ADD UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE;
;

